version: '3.8'
services:
  project-php-fpm:
    build:
      context: ./Dockerfile/php/
      dockerfile: Dockerfile
    image: fsb/project-php-fpm:7.0
    container_name: project-php-fpm
    hostname: project-php-fpm
    restart: always
    volumes:
      - ./php/app:/var/www/html
      - ./conf/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - back

  back:
    name: back
